-- MySQL Script generated by MySQL Workbench
-- Sat Apr  8 22:56:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paneldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paneldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paneldb` DEFAULT CHARACTER SET utf8 ;
USE `paneldb` ;

-- -----------------------------------------------------
-- Table `paneldb`.`Varos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Varos` (
  `irsz` INT NOT NULL,
  `varosNev` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  PRIMARY KEY (`irsz`),
  UNIQUE INDEX `irsz_UNIQUE` (`irsz` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Felhasznalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Felhasznalo` (
  `idFelhasznalo` INT NOT NULL AUTO_INCREMENT,
  `vezetekNev` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `keresztNev` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `irsz` INT NULL,
  `email` VARCHAR(30) NULL,
  `regDatum` DATETIME GENERATED ALWAYS AS (Today()) VIRTUAL,
  `jelszo` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `felhasznalo_nev` VARCHAR(10) NULL,
  PRIMARY KEY (`idFelhasznalo`),
  UNIQUE INDEX `idFelhasznalo_UNIQUE` (`idFelhasznalo` ASC) VISIBLE,
  INDEX `irsz_idx` (`irsz` ASC) VISIBLE,
  CONSTRAINT `irsz`
    FOREIGN KEY (`irsz`)
    REFERENCES `paneldb`.`Varos` (`irsz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`KepTipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`KepTipus` (
  `idKepTipus` INT NOT NULL,
  `kepTipusNev` VARCHAR(15) NULL,
  PRIMARY KEY (`idKepTipus`),
  UNIQUE INDEX `idKepTipus_UNIQUE` (`idKepTipus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Kepek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Kepek` (
  `idKep` INT NOT NULL AUTO_INCREMENT,
  `kepTipusID` INT NULL,
  `felhasznaloID` INT NULL,
  `feltoltDatum` DATETIME NULL,
  `kepMegj` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `kepFajlnev` VARCHAR(15) GENERATED ALWAYS AS ("k"+idKEP) VIRTUAL,
  PRIMARY KEY (`idKep`),
  INDEX `felhasznaloID_idx` (`felhasznaloID` ASC) VISIBLE,
  INDEX `kepTipusID_idx` (`kepTipusID` ASC) VISIBLE,
  UNIQUE INDEX `idKep_UNIQUE` (`idKep` ASC) VISIBLE,
  CONSTRAINT `felhasznaloID`
    FOREIGN KEY (`felhasznaloID`)
    REFERENCES `paneldb`.`Felhasznalo` (`idFelhasznalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kepTipusID`
    FOREIGN KEY (`kepTipusID`)
    REFERENCES `paneldb`.`KepTipus` (`idKepTipus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`ErkelyTipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`ErkelyTipus` (
  `idErkelyTipus` INT NOT NULL,
  `erkelyTipusNev` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  PRIMARY KEY (`idErkelyTipus`),
  UNIQUE INDEX `idErkelyTipus_UNIQUE` (`idErkelyTipus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Terkepresz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Terkepresz` (
  `idTerkepresz` INT NOT NULL AUTO_INCREMENT,
  `terkepFajlnev` VARCHAR(15) NULL,
  PRIMARY KEY (`idTerkepresz`),
  UNIQUE INDEX `idTerkepresz_UNIQUE` (`idTerkepresz` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Igazhamis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Igazhamis` (
  `idIgazhamis` TINYINT NOT NULL,
  `IgenNem` VARCHAR(4) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  PRIMARY KEY (`idIgazhamis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`LakasTipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`LakasTipus` (
  `idLakasTipus` INT NOT NULL AUTO_INCREMENT,
  `meret` INT NULL,
  `szobaSzam` INT NULL,
  `kulonWC` TINYINT NULL,
  `ablakosKinyha` TINYINT NULL,
  `erkelytipusID` INT NULL,
  `alaprajzID` INT NULL,
  PRIMARY KEY (`idLakasTipus`),
  UNIQUE INDEX `idLakasTipus_UNIQUE` (`idLakasTipus` ASC) VISIBLE,
  INDEX `erkelytipusID_idx` (`erkelytipusID` ASC) VISIBLE,
  INDEX `alaprajzID_idx` (`alaprajzID` ASC) VISIBLE,
  INDEX `kulonWC_idx` (`kulonWC` ASC, `ablakosKinyha` ASC) VISIBLE,
  CONSTRAINT `erkelytipusID`
    FOREIGN KEY (`erkelytipusID`)
    REFERENCES `paneldb`.`ErkelyTipus` (`idErkelyTipus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alaprajzID`
    FOREIGN KEY (`alaprajzID`)
    REFERENCES `paneldb`.`Kepek` (`idKep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kulonWC`
    FOREIGN KEY (`kulonWC` , `ablakosKinyha`)
    REFERENCES `paneldb`.`Igazhamis` (`idIgazhamis` , `idIgazhamis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Idoszak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Idoszak` (
  `idIdoszak` INT NOT NULL,
  `idoszak` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIdoszak`),
  UNIQUE INDEX `idIdoszak_UNIQUE` (`idIdoszak` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Lakotelep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Lakotelep` (
  `idLakotelep` INT NOT NULL AUTO_INCREMENT,
  `lakotelepNev` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `kerulet` VARCHAR(5) NULL,
  `terkepID` INT NULL,
  `idoszakID` INT NULL,
  `leiras` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `fokepID` INT NULL,
  PRIMARY KEY (`idLakotelep`),
  UNIQUE INDEX `idLakotelep_UNIQUE` (`idLakotelep` ASC) VISIBLE,
  INDEX `terkepID_idx` (`terkepID` ASC) VISIBLE,
  INDEX `fokepID_idx` (`fokepID` ASC) VISIBLE,
  INDEX `idoszakID_idx` (`idoszakID` ASC) VISIBLE,
  CONSTRAINT `terkepID`
    FOREIGN KEY (`terkepID`)
    REFERENCES `paneldb`.`Terkepresz` (`idTerkepresz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idoszakID`
    FOREIGN KEY (`idoszakID`)
    REFERENCES `paneldb`.`Idoszak` (`idIdoszak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fokepID`
    FOREIGN KEY (`fokepID`)
    REFERENCES `paneldb`.`Kepek` (`idKep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`LtpLakastipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`LtpLakastipus` (
  `lakotelepID` INT NOT NULL,
  `lakastipusID` INT NOT NULL,
  `darab` INT NULL,
  PRIMARY KEY (`lakotelepID`, `lakastipusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Otlet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Otlet` (
  `idOtlet` INT NOT NULL,
  `felhasznaloID` INT NOT NULL,
  `lakastipusID` INT NOT NULL,
  `megnevezes` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  `alaprajzValt` TINYINT NULL,
  `alaprajzID` INT NULL,
  `otletLeiras` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci' NULL,
  PRIMARY KEY (`idOtlet`),
  UNIQUE INDEX `idOtlet_UNIQUE` (`idOtlet` ASC) VISIBLE,
  INDEX `felhasznaloID_idx` (`felhasznaloID` ASC) VISIBLE,
  INDEX `lakastipusID_idx` (`lakastipusID` ASC) VISIBLE,
  INDEX `alaprojzID_idx` (`alaprajzID` ASC) VISIBLE,
  INDEX `alaprajzValt_idx` (`alaprajzValt` ASC) VISIBLE,
  CONSTRAINT `felhasznaloID`
    FOREIGN KEY (`felhasznaloID`)
    REFERENCES `paneldb`.`Felhasznalo` (`idFelhasznalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lakastipusID`
    FOREIGN KEY (`lakastipusID`)
    REFERENCES `paneldb`.`LakasTipus` (`idLakasTipus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alaprojzID`
    FOREIGN KEY (`alaprajzID`)
    REFERENCES `paneldb`.`Kepek` (`idKep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alaprajzValt`
    FOREIGN KEY (`alaprajzValt`)
    REFERENCES `paneldb`.`Igazhamis` (`idIgazhamis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`Galeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`Galeria` (
  `otletID` INT NOT NULL,
  `kepID` INT NOT NULL,
  PRIMARY KEY (`otletID`, `kepID`),
  CONSTRAINT `otletID`
    FOREIGN KEY (`otletID`)
    REFERENCES `paneldb`.`Otlet` (`idOtlet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paneldb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paneldb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
